nodejs/node-addon-api

- napi-inl.h
- napi.h
- Add an `AsyncWorker` class that is an equivalent of the one defined in `node_api_helpers.h` and `nan.h`, but done in the style of the other NAPI C++ wrappers.
 - Create new `ObjectReference` and `FunctionReference` classes that make it easy to get/set properties and call functions via a reference with automatic handle scoping. These are both used by `AsyncWorker`, but are also likely to be useful in other scenarios.
- Change many method parameters to accept NAPI primitives instead of NAPI classes. Since the classes are implicitly convertible to the primitives it doesn't affect passing class instances, but it makes it easier to interop with the NAPI C APIs that only use the primitives.
- Move the index getters and setters from `Array` to `Object`, because objects support indexed …
> AsyncWorker, ObjectReference, FunctionReference classes

- napi-inl.h
- napi.h
The C++ APIs for calling functions and defining properties required use of `std::vector`. While that's most flexible, a vector always allocates on the heap, which is costly and usually should not be necessary. This change adds alternative overloads everywhere `std::vector` is used, to allow `std::initializer_list` instead (that is very cheap, and sits on the stack). That makes the most common use of the APIs, where the arguments are specified using initializer-list syntax inline in the function call, very efficient. This change did yield a measurable performance improvement: approximately 5% improvement in the most extreme canvas benchmarks.
I also experimented with variadic template function arguments as an alternative to `std::initializer_list`. They might have offered a more natural …
> Enable initializer_list for function args

- README.md
- include_dirs.js
- index.js
- package.json
This enables other packages to get the N-API headers via a package dependency, the same way that NAN works. The header files would be referenced like this in `binding.gyp`: 
```json
'include_dirs': ["<!(node -p \"require('node-api').include\")"],
```
The same mechanism can be used in the future to enable referencing other things from the package like a static lib or maybe a gyp dependency, when we add the source code for back-compat.
Currently I've set a package name of **node-api**, with the expectation that we'll be able to [acquire that package name](https://github.com/laurie71/node-api/issues/2).
> Enable include files via package dependency

- napi-inl.h
- napi.h
- Remove the `PropertyName` class (wrapper around `napi_propertyname` type) and all uses of it.
- Add overloads for `Has()`, `Get()`, `Set()` that take `napi_value` parameters as an alternative to strings.
- Call the new `named_property` APIs where applicable.
- Add overloads for `Set()` that take `Napi::Value` parameters as an alternative to `napi_value`. I don't entirely understand why this is necessary, but it eliminates some compiler errors about ambiguous overload resolution.
- Make the `External` class templated on the type of external data that it holds.
- Support finalize hints
> Updates for N-API changes

- README.md
- index.js
- src/napi.h
- src/node_api.cc
- src/node_api.gyp
- src/node_api.h
- src/node_api_async.cc
- src/node_api_async.h
- src/node_api_async_internal.h
- src/node_api_async_types.h
- src/node_api_internal.h
- src/node_api_types.h
Adding logic to `index.js` and a `node_api.gyp` to enable conditional static-linking to N-API. See the updated `README.md` for more info. And we still need to figure out a good way to detect at runtime whether the current node engine has N-API built-in or not.
The `node_api*` files here are copied directly from https://github.com/nodejs/abi-stable-node/pull/167; see that PR for more details. Technically there is no reason those files need to be identical, but it makes maintenance much easier.
> Enable back-compat with pre-N-API node

- napi-inl.h
- napi.h
Updates for pending changes in async APIs at https://github.com/nodejs/abi-stable-node/pull/204, along with other recent changes.
- Rename `napi_work` to `napi_async_work`
- Async APIs all take an `env` parameter and return a `napi_status`
- New `napi_cancel_async_work()` API
- Track (a persistent reference to) an `Error` object for async work errors, rather than just an error message.
- Error handling APIs all return a `napi_status`
- Reference counts are unsigned
> Updates for N-API async changes

- napi-inl.h
- napi.h
- test/.gitignore
- test/binding.cc
- test/binding.gyp
- test/index.js
Hi all! :wave: I’ve decided to do a thing:
* 52c1aa9 makes it easier to create new functions (avoid compiler warnings about ambiguity when creating functions)
* 051eb13 adds support for `obj[key] = value` notation
* 4f2fe82 adds a small test for the 2 features mentioned above
Let me know what you think!
> Make Function::New more usable, support obj[…] for writing and add a small test

- napi-inl.h
- napi.h
- Make `Error::Message()` a proper `noexcept` method because it is
called by `what()`
- Mark the `_message` member of `Error` mutable instead of using
a `const_cast`, this is what `mutable` is there for.
> Minor Error handling refactor

- .gitignore
- README.md
- napi-inl.h
- napi.h
- package.json
- test/binding.cc
- test/binding.gyp
- test/error.cc
- test/error.js
- test/function.cc
- test/function.js
- test/index.js
- Set up a pattern for organizing a .cc and .js test files
roughly corresponding to each class to be tested
- Add unit tests for the Function and Error classes
- Update test binding.gyp file to build on Windows (fix quotes)
- Update test binding.gyp and README to enable exceptions with MSVC
- Fix type of CallbackInfo::This
> Set up unit tests

- napi-inl.h
- napi.h
- package.json
- test/arraybuffer.cc
- test/arraybuffer.js
- test/binding.cc
- test/binding.gyp
- test/buffer.cc
- test/buffer.js
- test/error.cc
- test/external.cc
- test/external.js
- test/function.cc
- test/function.js
- test/index.js
- Add optional callback data pointer to `Function::New()`
- Add overloads to all `New` methods that take a finalizer callback, to support templatized finalizer and finalize hint
- Add tests for `ArrayBuffer`, `Buffer`, `External`, and `Function` classes to verify the changed areas of code
- Fix bug in `ArrayBuffer` class found by tests (copy `EnsureInfo` pattern from `Buffer`)
Note that while the finalize hint parameter is templatized, the function callback data parameter is still just a `void*`.  I considered applying the a similar pattern there, but it started to get way too complicated. The challenge is the callback data becomes a property on the `CallbackInfo` class, so then that class would have to be templatized also. But that class is also used in the various method callbacks in …
> Pass through callback data and finalize hint

- napi-inl.h
- napi.h
- test/binding.cc
- test/binding.gyp
- test/object.cc
- test/object.js
Add static methods on the `Napi::PropertyDescriptor` class that provide convenient ways to construct `PropertyDescriptor` instances for different kinds of property descriptors. These are equivalent to the similar static methods on the `ObjectWrap` class, except they are for use when defining properties outside of an object-wrapping scenario. Callbacks are templatized (like with `Function::New()`) so that they can work with lambdas or regular function pointers.
New test cases cover the various overloads for constructing property descriptors and defining properties.
And the `Name` class constructors needed to be made public, to allow code like `value.As<Name>()`, that is used by the test.
> Add PropertyDescriptor creation methods

- napi-inl.h
- napi.h
- test/error.cc
- test/error.js
A `Napi::Error` instance must hold a persistent reference to the JS error object so that it can escape from handle scopes when thrown as a C++ exception.
Fixes: https://github.com/nodejs/node-api/issues/31
> Make Error a persistent reference

- napi-inl.h
- napi.h
- test/asyncworker.cc
- test/asyncworker.js
- test/binding.cc
- test/binding.gyp
- test/index.js
- Remove `MakeCallback()` overloads that defaulted to undefined receiver, because `node::MakeCallback()` requires an object.
- Use the async worker persistent object as the receiver of a worker callback
- Persist async errors as strings, because an `Error` object cannot be created outside of a JS context
- Remove overridable `AsyncWorker::WorkComplete()` because it wasn't useful and caused confusion. `OnOK()` and/or `OnError()` should be (optionally) overridden instead.
- Add tests to validate basic success and error scenarios for `AsyncWorker`
> Test and fix AsyncWorker

- .npmignore
- LICENSE.md
- README.md
- napi-inl.h
- napi.h
- package.json
- Change package name from "node-api" to "node-addon-api"
- Add license file
- Add contributors list to package.json and readme
- Add preliminary doc link to readme
> Prepare for publish to npm

- napi-inl.h
- napi.h
- Move the `details` namespace to the top of `napi-inl.h`, because
its declarations need to be present for some of its contents to
be used (`FinalizeData` in particular)
- Make `AsyncWorker::OnError` take a const `Error` reference, because
right now `AsyncWorker::OnWorkComplete` calls it with an rvalue ref
and `OnError` doesn’t need any non-const methods of `Error`.
- Remove a `HandleScope` from `Error::New`, because the `HandleScope`
constructor itself must be able to create an `Error` when handle scope
creation fails.
> Fix some build failures

- README.md
- external-napi/node_api.h
- index.js
- src/napi.h
Instead of making the path from which napi.h is included conditional
upon the Node.js version, make the path of node_api.h thusly
conditional. This way, no additional modification needs to be made to a
dependent's binding.gyp in order to add the EXTERNAL_NAPI preprocessor
directive when the C++ wrappers are not used.
By this mechanism the C++ wrapper napi.h will also refer to the correct
version of node_api.h.
~~Fixes https://github.com/nodejs/node-api/issues/40~~
Fixes https://github.com/nodejs/node-api/issues/41
> Include-path-juggle node_api.h instead of napi.h (#41)

- napi-inl.h
- napi.h
- package.json
- test/binding.cc
- test/binding.gyp
- test/index.js
- test/typedarray.cc
- test/typedarray.js
- Rename `TypedArray_<>` to `TypedArrayOf<>`.
- Remove the second template parameter from `TypedArrayOf<>`, because it can be (usually) inferred from the first parameter and is only needed at object construction time.
- Remove the `TypedArray::As*Array()` methods, which were redundant because they did the same thing as `Value::As()`.
- Add doc-comments to `ArrayBuffer`, `TypedArray`, and `TypedArrayOf<>` classes.
- Add tests for typed arrays.
> TypedArray improvements and tests

- package.json
- test/arraybuffer.cc
- test/arraybuffer.js
- test/buffer.cc
- test/buffer.js
- test/error.cc
- test/external.cc
- test/external.js
- test/index.js
- test/object.js
- test/testUtil.js
- Make GC tests (arraybuffer, buffer, external) async, to account for different GC behavior with different versions of V8 and ChakraCore, similar to https://github.com/nodejs/node/pull/13121
- In test/index.js, use the --napi-modules and --expose-gc command-line flags automatically
- Add missing entry for object tests in index.js.
- Remove check for writable attribute on accessor property descriptors; it should not be there according to the JS spec.
- Remove the explicit dependency on node-gyp in package.json. (NPM carries its own copy of node-gyp.)
> Make tests work on all Node versions

- napi-inl.h
- test/name.cc
- test/name.js
Resizing a `std::string` to the number of chars to be copied into it usually worked because of how `std::string` usually allocates a little more memory than what is requested. But sometimes there would be no extra capacity, so the `capacity()` value passed to `napi_get_value_string()` was too short by one (due to the null-terminator). The result was strings of certain lengths could have one char trimmed off the end.
> Fix off-by-one error for strings of certain sizes

- .travis.yml
- appveyor.yml
Run for this PR:
* https://ci.appveyor.com/project/addaleax/node-api/build/7
* https://travis-ci.org/addaleax/node-api/builds/234598724
Notably, builds are currently failing on Node 4 or 6 on macOS with:
```
/Users/travis/build/addaleax/node-api/src/../napi.h:6:10: fatal error: 'initializer_list' file not found
```
Everything else is green, though.
(Coverage doesn’t seem to be working quite yet but that might just be because tests are failing.)
> Set up CI services

- .travis.yml
- appveyor.yml
Travis run: https://travis-ci.org/jasongin/node-addon-api/builds/237732241
AppVeyor run: https://ci.appveyor.com/project/jasongin/node-api/build/3
All jobs in the matrix are passing with the exception of those that use node nightly builds, which fail due to https://github.com/nodejs/build/issues/743
> Update CI to include node 4, 6, 8, nightly, CC nightly

- napi-inl.h
- src/node_api.cc
- test/error.cc
- test/error.js
When a call to an N-API function caused an error for some reason other than a JS exception, the fallback error message "Error in native callback" was always reported because of incorrect logic in `Napi::Error::New()`.
Then that fix exposed a bug in `napi_get_last_error_info()`, which I have fixed here and also at https://github.com/nodejs/node/pull/13087
> Fix reporting of API error messages

- README.md
node-api is an existing package, so I was pretty confused when there was no tools folder!
> Update README conversion steps with package name

- .editorconfig
- .travis.yml
- README.md
- appveyor.yml
- napi-inl.h
- napi.h
- package.json
- test/arraybuffer.cc
- test/arraybuffer.js
- test/asyncworker.js
- test/binding.gyp
- test/buffer.cc
- test/buffer.js
- test/error.cc
- test/error.js
- test/external.cc
- test/external.js
- test/function.cc
- test/function.js
- test/name.cc
- test/name.js
- test/object.cc
- test/object.js
- test/typedarray.cc
- test/typedarray.js
Enable using the N-API C++ wrapper classes with or without C++ exceptions. See the updated `Napi::Error` class documentation for an overview of the developer experience.
- Add a `NAPI_CPP_EXCEPTIONS` preprocessor symbol that is defined when C++ exceptions are enabled.
- Add `Env::GetAndClearPendingException()` method.
- Add `Value::IsEmpty()` method.
- Update documentation on `Error` class to provide parallel explanation and examples for error-handling without C++ exceptions.
- Update README to mention optional C++ exception support.
- Define a `NAPI_THROW_IF_FAILED()` macro that throws either a C++ or JS exception depending on whether `NAPI_CPP_EXCEPTIONS` is defined.
- Define a `details::WrapCallback()` helper function that catches C++ exceptions thrown from callbacks, only if …
> Conditional support for C++ exceptions

- README.md
- doc/Doxyfile
- napi-inl.h
- napi.h
- package.json
- Add doc-comments to the `Boolean`, `Number`, `Symbol`, `Object`,
and `PropertyLValue` classes.
- Make `PropertyLValue` a nested class inside `Object`, because it
is only ever used by `Object` and would almost never be referenced
explicitly.
- Make some `Object` method parameter names more consistent.
- Add missing `Object::Set()` overload.
> Add more documentation

- napi-inl.h
- napi.h
- test/error.cc
- test/function.cc
- test/index.js
- test/name.cc
- test/object.cc
- test/typedarray.cc
VS2013 issues
* No constexpr support
- Conditionally use constexpr if the compiler supports it
- Updated tests to use a macro for this purpose
* Requires copy constructor support for base classes of thrown objects
- Added a protected copy constructor to ObjectReference and
Reference<T>
* Incorrect overload resolution for std::initializer_list
- Used explicit types to invoke the correct overload
* No literal support for char16_t
- Added macro to convert the text properly
* Lambdas are unable to capture function non-pointers
- Updated the typedef to create a function pointer
* Short lifetime for temporary objects passed to constructors
- Updated the tests to create the objects and pass them to the
constructor. This is closer to how they would be used anyway
General improvements
* Added …
> Add support for VS2013

- napi-inl.h
- napi.h
While migrating some code from v8/nan to N-API, I encountered some situations where arguments were stored in a stack-allocated array. The exact number of arguments was not known in advance, though a (small) maximum was known. The C++ API currently requires using a `std::vector` when the number of arguments is variable. But `std::vector` always allocates on the heap, which is slower. This change adds overloads for raw argument array pointers, to support stack-allocated argument arrays. (And really any other allocation mechanism.)
> Pass func args as array in addition to vector, initializer list

- napi-inl.h
- napi.h
> Move napi_wrap into ObjectWrap constructor

- napi-inl.h
- napi.h
- test/object.cc
- test/object.js
Previously, various utility overloads of `Object::Set()` were provided. This was problematic, because accidental unexpected conversions could happen (e.g. `const char*` to `bool`) and overloads were ambiguous (e.g. `int` could be cast to `double` and `bool` and therefore could not be passed directly).
To address this, pass a template parameter instead, and introduce a helper `Value::From` method that could create a value based on the type of object it receives, and that uses clear precedence rules for determining the kind of JS value to create.
Fixes: https://github.com/nodejs/node-addon-api/issues/86
Also: Note that we can, if we want, extend this facility a lot, e.g. by turning iterable C++ types into arrays or `std::unordered_map`s into objects, and so on. I'd be happy to work on that, …
> Refactor property setting

- src/node_api.gyp
- src/node_internals.cc
- test/function.js
- test/typedarray.js
* Implement node::MakeCallback between 8.0.0 and 8.6.0 to fix
unresolved symbol
* Fix error message expectation (was: "Invalid pointer", is: "Invalid
argument")
> Fix test errors

- napi-inl.h
- test/basic_types/value.js
As discussed in the issue[1], IsObject() should return true for a
function.
[1] https://github.com/nodejs/node-addon-api/issues/207
> Make IsObject() allow functions

- CODE_OF_CONDUCT.md
The address specified in the current CODE_OF_CONDUCT.md is https://github.com/nodejs/TSC/blob/master/CODE_OF_CONDUCT.md.
But I think URL link seems to have been changed to admin. 
It is my first PR for node-addon-api repo.
> Fixed Code of conduct link properly

- doc/bigint.md
- napi-inl.h
- napi.h
- test/bigint.cc
- test/bigint.js
- test/binding.cc
- test/binding.gyp
- test/index.js
- test/typedarray.cc
- test/typedarray.js
blocked until https://github.com/nodejs/node/pull/21226 lands
> bigint support

- README.md
Updated the links for the examples, because recently we reactivated the repo [https://github.com/nodejs/node-addon-examples/](https://github.com/nodejs/node-addon-examples/) and now we use it to reference all our examples.
> Changed links of the examples to point to new node-addon-examples repo

- README.md
- doc/creating_a_release.md
I modified "node-add-api" to "node-addon-api".
> doc: fix typo

- index.js
The existing logic did not account for
semver minor bumps.
> src: fix selection logic for 6.x

- doc/setup.md
Added section to remember the macOS user to add the `-fvisibility=hidden` flag.
> Document adding -fvisibility=hidden flag for macOS users

- doc/basic_types.md
Add a blurb to the `Napi::Array` documentation that refers readers to
`Napi::TypedArray` and `Napi::ArrayBuffer` for using arrays with large
amounts of data.
> doc: refer to TypedArray and ArrayBuffer from Array

- doc/object.md
Some statements on code example are incorrect and generate errors.
> Little fix on code example

- doc/string.md
This is a drive-by PR to document the String::New functions that take non null-terminated strings.
> string.md: Document existing New(env, value, length) APIs

- doc/threadsafe_function.md
Re: https://github.com/nodejs/node-addon-api/pull/442
> doc: document ThreadSafeFunction

- doc/async_worker.md
Fixed typos in async_worker.md.
> doc: fix minor typo

- napi-inl.h
- napi.h
- test/index.js
- test/threadsafe_function/threadsafe_function.cc
Some users are experimenting compilation problem like reported in this issue: https://github.com/nodejs/node-addon-api/issues/517. I added a check if `NAPI_VERSION` is greater than 3 and in this case I enable the `Napi::ThreadsafeFunction`. Please review quickly.
> Fix compilation breakage on 1.7.0

- .travis.yml
- test/basic_types/array.cc
-----
As ci.nodejs.org doesn't automatically run for PRs, travis is still the easiest way to determine if the PR is test passed on multiple node variants and platforms.
1. node-chakracore v8 doesn’t expose napi version
2. node-chakracore v10 doesn’t throws on handlescope double escape
3. set npm_config_NAPI_VERSION to override NAPI_EXPERIMENTAL expansion
on Node.js version lower than 11 for napi_date_* not back ported to v10
> ci: enable travis for fast PR check

- .travis.yml
- napi-inl.h
- napi.h
- test/bigint.cc
- test/binding.cc
- test/binding.gyp
- test/date.cc
- test/index.js
- test/typedarray.cc
NAPI_EXPERIMENTAL would be expand to NAPI_VERSION=2147483647 if
NAPI_VERSION is not defined. It would be not compatible with various
Node.js versions if we use NAPI_VERSION > 2147483646 mixed with
definition of NAPI_EXPERIMENTAL. This fix introduced NODE_MAJOR_VERSION
to allow more precise control over test sets that which set should be
enabled on a Node.js release.
Refs: https://github.com/nodejs/node-addon-api/pull/534#discussion_r321590943
------
Since experimental api tests were conditioned by NODE_MAJOR_VERSION, we could simply run tests with `npm test` on every Node.js LTS version.
------
Strictly aligning with Node.js header js_native_api.h in which
napi_bigint related apis were nested in NAPI_EXPERIMENTAL.
> test: conditional test experimental features with NODE_MAJOR_VERSION

- doc/threadsafe_function.md
- napi-inl.h
- test/binding.cc
- test/binding.gyp
- test/index.js
- test/threadsafe_function/threadsafe_function_existing_tsfn.cc
- test/threadsafe_function/threadsafe_function_existing_tsfn.js
Fixes: https://github.com/nodejs/node-addon-api/issues/556
> tsfn: support direct calls to underlying napi_tsfn

- doc/class_property_descriptor.md
Return type should be void and second function argument of type Napi::Value should be present.  
See typedef:   
https://github.com/nodejs/node-addon-api/blob/295e560f5554c87d0a9dde6b73942ebd85fddb9d/napi.h#L1623
> Fix example code in doc/class_property_descriptor

- napi-inl.h
- test/binding.cc
- test/binding.gyp
- test/index.js
- test/threadsafe_function/threadsafe_function_ctx.cc
- test/threadsafe_function/threadsafe_function_ctx.js
Fixes: https://github.com/nodejs/node-addon-api/issues/581
> tsfn: add error checking on GetContext

- README.md
As far as I can tell, node-addon-api does not fall under the responsibility of any working group.
> Change "WG" to "team"

- doc/object.md
- doc/value.md
Fixed all the links to `Napi::Array` documentation.
Fixes issue https://github.com/nodejs/node-addon-api/issues/612
> [doc] Fixed links to array documentation

- doc/string.md
- doc/symbol.md
1. "ANSI" is misleading and not a good description of any string encoding. It is commonly used to refer to "Windows code pages" such as Windows-125x, but these code pages have never been standardized by ANSI.
2. It is wrong, we treat `std::string` as UTF8.
> Fix std::string encoding

- doc/object.md
Fixes: https://github.com/nodejs/node-addon-api/issues/614
> Add GetPropertyNames, HasOwnProperty, Delete

- doc/function.md
I've seen complains that there is no documents on napi/node-addon-api alternatives for `uv_async_t`s.  Link `Napi::ThreadSafeFunction` from JS function docs to highlight the option.
> doc: link threadsafe function from JS function

- doc/bigint.md
Link to the source code: https://github.com/nodejs/node-addon-api/blob/7f56a78ff7eab77f1316696aef1de3304b70e639/napi.h#L349-L352
> doc: Add Napi::BigInt::New() overload for uint64_t

- README.md
I provided to add badge section to readme. The link for N-API v6 badge is broken because we need to review and merge the PR https://github.com/nodejs/abi-stable-node/pull/394.
> Added badge section to documentation.

- napi-inl.h
We need to cast the `nullptr` to the templated type of the
`AsyncProgressQueueWorker`.
> src: fix AsyncProgressQueueWorker compilation

- doc/bigint.md
Fixes: issue **[745](https://github.com/nodejs/node-addon-api/issues/745)**
> doc: BigInt::ToWords docs not consistent with implementation

- napi-inl.h
- napi.h
Add guards to the threading apis because they are not supported in wasm32.
> src: add __wasm32__ guards

- appveyor.yml
Also updates to VS2017 so tests will compile - see #766 for further context.
Example successful build - https://ci.appveyor.com/project/lovell/node-addon-api/builds/34119509
Appveyor doesn't appear to currently run for PRs etc, so someone with the relevant access level to this repo may need to switch it back on again.
> Windows CI: synchronise Node.js versions with those used for Linux/macOS CI

- doc/function.md
Added required `return` only for the sake of completeness. 
When current example was compiled, it was returning the following error: "Error C4716: 'Init': must return a value". Now it is fixed.
> doc: Added required return to example

- README.md
This PR adds a link to the N-API tutorial website to the repo's `README` file.
> doc: add link to n-api tutorial website

- README.md
- doc/error.md
- doc/hierarchy.md
There is no reason to use plain HTTP, it only makes things easier to track/hijack for ISPs and other untrustworthy entities.
> doc: avoid directing users to HTTP

- doc/async_worker_variants.md
The old documentation was not very clear on how to use the API. It was missing javascript references, and was not necessarily following the best coding standards.
These adjustments make it a bit more complete now by providing all three necessary parts, the worker, the hookup code, and the javascript usage of it.
I have also gone ahead and rewritten the `AsyncProgressQueueWorker` example to show demonstration of the `FunctionReference` class and how to use multiple callbacks instead of one combined callback.
> Clean up AsyncProgressWorker documentation

- .clang-format
- .travis.yml
- package.json
- scripts/clang-format.js
This extends #819 with a pre-commit hook to run the `lint` task prior to making a git commit. 
For example, after I installed the package and tried to make a commit via:
> git commit -m "build: add pre-commit package for linting"
I received this error, because the linting failed:
```
... output from lint task giving needed code changes ...
+                              0,
+                              1,
+                              testData,
+                              std::function<decltype(AcquireFinalizerCallback)>(
+                                  AcquireFinalizerCallback),
+                              testData);
Object result = Object::New(env);
result["createThread"] = Function::New( env, CreateThread, "createThread", testData);
ERROR: please run "npm run lint:fix" to …
```
> build: add pre-commit package for linting

- package.json
- tools/README.md
- tools/clang-format.js
Fixes unexpected failure of lint on https://github.com/nodejs/node-addon-api/pull/832#issuecomment-728809368
> fix: git-clang-format doesn't recognize no changes requested on given files

- README.md
- test/index.js
Fixup testing for a specific N-API version
and document.
> test: fixup testing for specific N-API version

- package-support.json
- package.json
Add support info as per:
https://github.com/nodejs/package-maintenance/blob/main/docs/PACKAGE-SUPPORT.md
> doc: add support info

- tools/clang-format.js
Refs: #https://github.com/nodejs/node-addon-api/pull/840#issuecomment-735895055
> tools: print more instructions on clang-format check failed

- README.md
Refs: https://github.com/nodejs/node-addon-api/issues/684
> doc: clarify when to use N-API

- package.json
Fixes complains like this:
```javascript
$ npm run lint:fix
Configuration file(s) do(es) not support JavaScript: /workspace/node-addon-api/.clang-format
```
> script: fix complains that js files are not supported on npm run lint:fix

- .github/workflows/ci.yml
- .github/workflows/linter.yml
Run tests on GitHub Actions as the Travis runner doesn't seem to be running for a long time.
> chore: setup github actions for tests

- doc/threadsafe.md
This PR addresses the erroneous implementation documentation found in #859
> doc: fix tsfn docs to reflect true implementation

- .travis.yml
- CODE_OF_CONDUCT.md
- README.md
- appveyor.yml
- doc/array.md
- doc/cmake-js.md
- doc/property_descriptor.md
- doc/setup.md
URL references to GitHub resources with `HEAD` in the path will resolve to the correct default branch whether it's `master` or `main`. 
This PR should complete the repo's migration from the default branch of `master` to `main`. 
See https://github.com/nodejs/abi-stable-node/issues/421
> doc: Update GitHub URL references from 'master' to 'HEAD'

- README.md
- doc/typed_threadsafe_function.md
From what I've been told, `targetted` and `targetting` are uncommon at best, and considered wrong in most contexts. (I am not a native English speaker, though.)
> doc: fix spelling of "targeted" and "targeting"

- tools/clang-format.js
The `ChildProces` object `result` does not have an `error` property. We
should use `stderr` instead.
> tools: fix error detection

- doc/object.md
- doc/propertylvalue.md
Documents the helper class `Napi::Object::PropertyLValue`.
Fixes: https://github.com/nodejs/node-addon-api/issues/924
> doc: add propertylvalue.md

- test/function.cc
- test/function.js
- tools/clang-format.js
This PR adds tests for every Function method.
I splitted the changes in commits so the diff is easier to follow.
EDIT :thinking:
```
All tests passed!
Tests aborted with SIGSEGV
```
> Function tests

- doc/object.md
This PR fixes the documentation for:
```cpp
Napi::Object::Object(napi_env env, napi_value value);
```
> doc: fix documentation for object api.

- doc/reference.md
- napi.h
Not sure how this ever made its way into the API, but people should *never* use this.
> doc: warn about SuppressDestruct()

- package.json
- tools/clang-format.js
This PR fixes following issues:
1. `tools/clang-format` suggested an incorrect format (redundant quotes) of fix command;
2. `npm run lint` and `npm run lint:fix` run the clang-format on a different set of changes: `tools/clang-format` (`npm run lint`) compares between two commits, while `git-clang-format` without commits argument (`npm run lint:fix`) compares workspace changes with `HEAD`. This makes pre-commit hooks hard to predict in various conditions.
Refs: https://github.com/nodejs/node-addon-api/pull/938#issuecomment-802161908
> chore: fixup linter commands

- doc/object.md
- doc/property_descriptor.md
- napi-inl.h
There is an argument to be made for using tabs, but the mixture of tabs and spaces causes visual inconsistencies in the docs and source code.
> Fix tab indent

- doc/object.md
The list of types that are valid for the `value` argument of `Napi::Object::Set` is inaccurate. Instead of trying to maintain it, let's just add a reference to `Napi::Value::From` since any argument to `Napi::Object::Set` is passed to `Napi::Value::From` anyway.
> doc: sync Object::Set value arg with Value::From

- doc/array_buffer.md
- doc/buffer.md
Fixes: https://github.com/nodejs/node-addon-api/issues/258
This PR add some warnings on documentation for:
```cpp 
static Napi::Buffer<T> Napi::Buffer::New(napi_env env, T* data, size_t length);
static Napi::ArrayBuffer Napi::ArrayBuffer::New(napi_env env, void* externalData, size_t byteLength);
```
> doc: added some warnings for buffer and array buffer factory method.

- README.md
This PR add new badges for Node-API v7 and v8.
The PR should be landed after:
- https://github.com/nodejs/abi-stable-node/pull/428
- https://github.com/nodejs/node-addon-api/pull/951
> Added badges for Node-API v7 and v8.

- doc/version_management.md
> doc: correct struct definition

- doc/setup.md
> fix: key for wapping drawing's system condition

- .github/workflows/ci-win.yml
- .github/workflows/ci.yml
Node.js v16.x will be the next LTS line in 6 months.
> build: add Node.js v16.x to CI

- doc/object.md
- doc/object_reference.md
- napi-inl.h
- napi.h
- test/object/object.cc
- test/object/set_property.cc
- test/object/set_property.js
If c++ exception is disabled, there is no ergonomic way to detect
failtures on void returning.
> src: return bool on object set and define property

- napi-inl.h
- napi.h
- test/common/index.js
- test/object/object_freeze_seal.cc
- test/object/object_freeze_seal.js
These operations can call into JavaScript by using Proxy handlers,
hence JavaScript exceptions might pending at the end of the operations.
This is not a breaking change.
> src: return bool on object freeze and seal

- except.gypi
- noexcept.gypi
In this PR I changed the way we used to enable or disable the C++ expection support for the entire test suite. For more information about this change see the previous PR https://github.com/nodejs/node-addon-api/pull/1059.
> test: fixed the way to enable C++ exceptions.

- doc/setup.md
This PR fixes the documentation about how to enbale C++ exception. The problem was identified the first time in this issue: https://github.com/nodejs/node-addon-api/issues/85. In Windows system is not enough add the following configuration on `binding.gyp`:
```
'msvs_settings': {
'VCCLCompilerTool': { 'ExceptionHandling': 1 },
},
```
but it's necessary override the defined `_HAS_EXCEPTIONS` macro and set it to 1. 
In the `common.gypi` (see:  https://github.com/nodejs/node/blob/master/common.gypi#L273) the `_HAS_EXCEPTIONS` has been set to 0 to make sure the STL doesn't try to use exceptions, but in the addons with the support for C++ it needs to be changed to 1 otherwise the exceptions system could be catch the wrong exception.
> doc: fix documentation about how to enable C++ exception

- doc/object_wrap.md
> docs: fix typo and formatting

- napi-inl.h
- test/function.cc
- test/function.js
Function::New fails to compile when given a move-only functor. For
example, when constructing a callback function for Promise#then, a
lambda might capture an ObjectReference. Creating a Function for such a
lambda results in a compilation error.
Tweak Function::New to work with move-only functors.
For existing users of Function::New, this commit should not change
behavior.
> src,test: allow creating Function with move-only functor

- .github/workflows/ci.yml
Looks like github no longer has ubuntu 16 so we'll
need to update the compiler and remove 10.x testing.
> test: update compiler used for testing

- doc/addon.md
Add a blurb explaining that using `Napi::Addon<T>` entails avoiding the
use of `Napi::Env::SetInstanceData()`.
Fixes: https://github.com/nodejs/node-addon-api/issues/1097
> doc: add blurb about SetInstanceData

- .github/workflows/ci-win.yml
- README.md
> Testing CI run

- napi-inl.h
- napi.h
- test/function.cc
- test/function.js
Adds an override to Napi::Function::Call so that you can call it with a c-style array of Napi::Value's
> Add Function::Call Napi::Value override

- napi-inl.h
- napi.h
- package.json
- test/binding.gyp
- test/common/index.js
- test/common/test_helper.h
- test/error_terminating_environment.js
- unit-test/binding.gyp
Enable support for a `NAPI_CPP_CUSTOM_NAMESPACE` that would wrap
the `Napi` namespace in a custom namespace.
This can be helpful when there are multiple parts of a compiled
shared library or executable that depend on `node-addon-api`,
but different versions of it. In order to avoid symbol conflicts
in these cases, namespacing can be used to make sure that the
linker would not merge definitions that the compiler potentially
generates for the node-addon-api methods.
> src: enable wrapping Napi namespace with custom namespace

- doc/object_wrap.md
Refs: https://github.com/nodejs/node/pull/42461
We currently defer finalizer callbacks until the loop is idle.
Warn users that the weak reference on `ObjectWrap` isn't guaranteed to be valid just because the object hasn't been finalized (destructed) yet.
> doc: clarify ObjectWrap weak ref behavior

- doc/class_property_descriptor.md
Added some comments to explain that `Napi::ClassPropertyDescriptor` is a helper class created in `Napi::InstanceWrap<T>` and `Napi::ObjectWrap<T>`.
See: https://github.com/nodejs/node-addon-api/issues/1106
> doc: added some comments to ClassPropertyDescriptor.

- test/async_context.cc
- test/async_context.js
Add unit test for async context. This will close this github issue:  https://github.com/nodejs/node-addon-api/issues/1038
> Add test coverage for async contexts

- tools/eslint-format.js
A small fix for `eslint-format` based on the issue https://github.com/nodejs/node-addon-api/issues/1175. At the moment `npm run lint/fix` is failing silently on windows because it cannot find `eslint` cmd on windows and we do not check for that.
> Add condition for window to find eslint

- test/function.cc
- test/function.js
- unit-test/README.md
- added basic unit test for CallbackInfo NewTarget() method
- corrected npm script references in `unit-test/README.md` (for focused test runs)
> test: CallbackInfo NewTarget unit test

- README.md
Document all possible filter conditions added in https://github.com/nodejs/node-addon-api/pull/1078
> Update Readme for filter conditions in unit tests

- .github/workflows/ci-win.yml
- .github/workflows/ci.yml
- .github/workflows/linter.yml
- .github/workflows/stale.yml
This PR changes versions of components used in CI to the latest available:
-  node-version: [12.x, 14.x, 16.x] -> [14.x, 16.x, 18.x] _(version 12 is not supported anymore)_
- ubuntu-18.04 -> ubuntu-latest
- actions/checkout@v2 -> actions/checkout@v3
- nvs -> actions/setup-node@v3
- actions/setup-node@v1 -> actions/setup-node@v3
- actions/setup-node@v2.1.5 -> actions/setup-node@v3
- actions/stale@v4 -> actions/stale@v5
> Update CI component versions

- test/typed_threadsafe_function/typed_threadsafe_function_unref.cc
- test/typed_threadsafe_function/typed_threadsafe_function_unref.js
We currently do not have a test for testing the `Ref(Env env)` function attached to the TSFN class. But I am not too sure if this is the best way to test this functionality. From what I understand this method is a wrapper around `napi_ref_threadsafe_function` which prevents the event loop from exiting until the tsfn gets destroyed by a call to `Release()`. 
My thought behind this approach is that we first reference this TSFN function, before the callback in `setTimeout`  Unref's the TSFN which causes the event loop to exit. Though it appears that this tsfn should already be referenced prior to calling `Ref`, and `napi_ref_threadsafe_function` is idempotent so it has no effect.  Is there a better approach to test this method? Also in what scenarios would `napi_ref_threadsafe_function` or …
> test: Add test coverage for "TSFN::Ref()"

- test/index.js
process.config is now read-only. Remove
attempt to update it. This may break the ability
to run tests in debug mode but is needed to get ci running again.
> test: remove update to process.config

- doc/handle_scope.md
> doc: add HandleScope example

- test/async_worker.cc
- test/async_worker.js
Adding a small test case for Async workers' `Cancel`  functionality, where if the cancellation is successful neither `OnOk` or `OnError` should be invoked.
> test: Add test case for canceling async worker tasks

- test/async_worker.cc
- test/async_worker.js
A follow up to https://github.com/nodejs/node-addon-api/pull/1202#discussion_r974497323. Adding a test for checking when a task cancellation is unsuccessful (task is already queued and executing).
> test: Add test cased for failed task cancellations

- .github/workflows/stale.yml
From `actions/stale@v2` the option for exempt labels was renamed to `exempt-issue-labels` (plural). Also it appears that this repository is using [`never-stale`](https://github.com/nodejs/node-addon-api/issues?q=is%3Aissue+is%3Aopen+label%3Anever-stale) (with a hyphen instead of a space character).
Refs: https://github.com/actions/stale/pull/19
> chore: fix stale workflow

- test/typed_threadsafe_function/typed_threadsafe_function_ctx.cc
- test/typed_threadsafe_function/typed_threadsafe_function_ctx.js
Adding test coverage for `TSFN::New` overloads where we provide the async resource name and/or the async resource object but no finalizer callbacks.
> test: Add test coverage to TSFN::New() overloads

- .github/workflows/ci-win.yml
- .github/workflows/ci.yml
In this PR we are adding `windows-2022` OS image to the CI to test Node-API with Visual Studio 2022.
We are also adding verification for Node.JS version 19.x.
The new verification matrix for Windows is:
- `windows-2022` - Node,JS [ `16.x`, `18.x`, `19.x` ]
- `windows-2019` - Node,JS [ `14.x`, `16.x`, `18.x`, `19.x` ]
Note that VS 2022 is not supported by Node.JS 14.x GYP and it is not in the matrix.
For the MacOS and Ubuntu we have added printing of compiler version.
It helped to identify that:
- On MacOS the `gcc` is an alias for `clang`. So, we are removing the `MacOS + gcc` from the test matrix.
- On Ubuntu the condition `"${{ matrix.os }}" = ubuntu-*` seems to always fail and we never install the GCC version 6.5. Fixing this condition caused the script error because the package could …
> chore: add Windows with VS 2022 and Node.JS 19.x to the CI matrix

- test/threadsafe_function/threadsafe_function.cc
- test/threadsafe_function/threadsafe_function.js
Added test coverage for `ThreadSafeFunction` 's missing `NonBlockingCall` function overloads. In particular test cases for when we pass just the single `js` function into the tsfn, or nothing at all.
> test: Add tests for ThreadSafeFunction's NonBlock function overloads

- test/objectwrap.cc
- test/objectwrap.js
Completes test coverage for https://github.com/nodejs/node-addon-api/issues/993
> test: Add test covg for obj wrap

- test/async_progress_worker.cc
This PR aims to fix https://github.com/nodejs/node-addon-api/issues/1290
> test: Update wait with a condition

- doc/env.md
I'm 99% sure that this was a typo that was then copy-pasted, but if not, please close.
> Fix exits/exists typo in docs for Env::AddCleanupHook()

- doc/value.md
- napi-inl.h
- napi.h
- test/binding.gyp
- test/value_type_cast.cc
- test/value_type_cast.js
Fixes https://github.com/nodejs/node-addon-api/issues/1246
> src: enforce type checks on Napi::Value::As()

- test/async_progress_queue_worker.cc
- test/async_progress_queue_worker.js
Resolves https://github.com/nodejs/node-addon-api/issues/1043.
Similar to PR https://github.com/nodejs/node-addon-api/pull/1307 but for AsyncProgressQueueWorker
> [Test] Add tests for async progress queue worker

- .github/workflows/ci-win.yml
- .github/workflows/ci.yml
- README.md
- doc/creating_a_release.md
Adds documentation for how to drop support, as well as dropping support for Node.js v14 and v19.
Relates: https://github.com/nodejs/node-addon-api/issues/1315
> doc,chore: drop support for Node.js v14, v19

- README.md
- doc/hierarchy.md
- doc/syntax_error.md
- napi-inl.h
- napi.h
- test/error.cc
- test/error.js
Adds wrapper for `Napi::SyntaxError` from release of Node-API v9.
> src: add SyntaxError

- package.json
Assumed from last Changelog the current version supports Node.js 16, 18, 20 and we should also not block 21+ for now, Right?
fixes #1339
> Add Node.js version restrictions

- doc/async_worker_variants.md
Hey guys, I found there are some mixing around `ExecutionProcess` and `ExecutionProgress` in the documentation doc/async_worker_variants.md. And I looked up in the src code and didn't find anything about 'ExecutionProcess'. I only found the inner class `ExecutionProgress` in `AsyncProgressWorker` and `AsyncProgressQueueWorker`.
So is this a typo? Tell me if I'm wrong.
> Doc: fix typo 'Napi::AsyncProgressWorker::ExecutionProcess' to 'Napi::AsyncProgressWorker::ExecutionProgress'.

- napi-inl.h
- napi.h
The constructor of the Uint8Array has called `napi_get_typed_array_info`,
which should be identical to `napi_get_buffer_info`. Remove the duplicated
napi_get_buffer_info call.
Refs: https://github.com/nodejs/node/pull/48742
> src: remove duplicate buffer info calls

- .gitignore
- benchmark/binding.gyp
- common.gypi
- doc/setup.md
- index.js
- node_addon_api.gyp
- test/binding.gyp
Fixes: https://github.com/nodejs/node-addon-api/issues/1379
As documented at https://gyp.gsrc.io/docs/InputFormatReference.md#processing-order, a dependency's setting is processed after merging the root target_defaults, and variable expansion is allowed in dependency specifiers. This allows addons to include node-addon-api and common configs with a single line of gyp config. For example, when the addon needs c++ exception feature, they can simply declare the dependency on `node-addon-api-except`:
```
{
"targets": [
{
"target_name": "my_node_addon",
"sources": [
"src/my_node_addon.cc"
],
'dependencies': [
"<!(node -p \"require('node-addon-api').targets\"):node_addon_api_except"
]
}
]
}
```
No need to copy a paragraph of configs into addons' binding.gyp like documented at …
> gyp: add common targets

- doc/setup.md
Without proper indentation, some paragraphs would be rendered as code blocks:
> doc: fix rendering of code blocks in list

- README.md
- doc/array.md
- doc/cmake-js.md
Due to reorganization of examples into categorized folders in node-addon-examples library, links in docs and readme got broken. Fixed all the links.
> Fixed Broken Links in Docs and Readme

- .github/dependabot.yml
Dependabot creates a lot of trivial updates of dependencies. See https://github.com/nodejs/node-addon-api/releases/tag/v7.1.0.
This patch reduces the noise that can created by the dependabot by grouping the updates and reducing the frequency of PRs.
> chore: reduce dependabot noise

- .github/workflows/ci-win.yml
- .github/workflows/ci.yml
- .github/workflows/linter.yml
- README.md
Add v21.x runs as well.
Refs: https://github.com/nodejs/node-addon-api/issues/1381
> chore: remove v16.x regular CI runs

- .github/workflows/coverage-linux.yml
- package.json
- test/binding.gyp
The result looks pretty decent at first blush:
AFAICT, this only works on Linux, and doesn't integrate with any online coverage tools.
> test: add basic coverage support

- .gitignore
- napi-inl.h
- napi.h
- test/async_worker.cc
Fix PR fixes compilation errors and warnings while compiling code in VS 2022.
- async_worker.cc used deprecated `std::allocator` APIs. Their use is is replaced with APIs that is still valid.
- There was a strange error in `ObjectWrap<T>::WrappedMethod`. It was saying that `&` operation requires an l-value. The issue is fixed by copying `method` pointer to a local variable before invocation.
- VS identified that some fields were not initialized. They are changed to initialize with `{}`.
- VS identified that some functions must be `noexcept`. They are augmented with `NAPI_NOEXCEPT`.
> fix compilation for Visual Studio 2022

- index.js
- package.json
- test/exports.js
- tools/conversion.js
This PR contains a proposal to expose the package `version` property in the public API.
The `version` value is already used by the conversion tooling and is additionally useful in external contexts too, for example when specifying/detecting `node-addon-api` as an optional and/or peer dependency.
This would bring `node-addon-api` in line with `node-gyp`, which already exports `require('node-gyp').version`. The change in the PR will allow me to improve the install-time detecting/logging for `node-addon-api` within `sharp`.
It also adds a test with expectations for this property as well as all existing exported properties.
> Expose version property in public API

- .github/workflows/ci-win.yml
- .github/workflows/ci.yml
- common.gypi
- napi-inl.h
- test/addon_build/tpl/binding.gyp
Since we made the default for Node.js core finalizers synchronous for users running with `NAPI_EXPERIMENTAL` and introduced `env->CheckGCAccess()` in Node.js core, we must now defer all finalizers in node-addon-api, because our users likely make non-gc-safe Node-API calls from existing finalizers. To that end,
* Use the NAPI_VERSION environment variable to detect whether `NAPI_EXPERIMENTAL` should be on, and add it to the defines if `NAPI_VERSION` is set to `NAPI_VERSION_EXPERIMENTAL`, i.e. 2147483647.
* When building with `NAPI_EXPERIMENTAL`,
* render all finalizers asynchronous, and
* expect `napi_cannot_run_js` instead of `napi_exception_pending`.
> src: restore ability to run under NAPI_EXPERIMENTAL

- napi-inl.h
- napi.h
Print actual value type if the check failed.
> src: improve messages on CheckCast

- .github/workflows/release-please.yml
- .release-please-manifest.json
- README.md
- doc/contributing/creating_a_release.md
Refs: https://github.com/nodejs/node-addon-api/pull/1526#issuecomment-2197234632
> chore: update release document

- .github/workflows/release-please.yml
- .release-please-manifest.json
- release-please-config.json
Fix release-please config since googleapis/release-please-action ignores config file when `release-type` present in the action input.
Refs: https://github.com/googleapis/release-please-action/blob/7987652d64b4581673a76e33ad5e98e3dd56832f/src/index.ts#L86
Example PR: https://github.com/legendecas/node-addon-api/pull/11
> chore: fix release-please config

- .github/workflows/linter.yml
- CHANGELOG.md
- README.md
- package.json
* \[[`16882e7da2`](https://github.com/nodejs/node-addon-api/commit/16882e7da2)] - _**Revert**_ "Add Node.js version restrictions (#1340)" (Chengzhong Wu)
> v7.1.1 Release Proposal

- release-please-config.json
By default release-please creates a tag with component names: https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#subsequent-versions
There is only one component in the repo so there is no need to include component name in tag name.
Refs: https://github.com/nodejs/node-addon-api/releases/tag/node-addon-api-v8.1.0
> chore: do not include component name in tag

- .github/workflows/ci-win.yml
> chore: enable experimental testing in ci-win.yml

- napi-inl.h
Call no-op `ObjectWrap<T>::Finalize` if user does not provide a `Finalizer` method.
Fixes: #1573
> fix: call base basic finalizer if none defined

- doc/value.md
- napi-inl.h
- napi.h
- test/async_worker.cc
- test/binding.gyp
- test/function.js
- test/globalObject/global_object_delete_property.cc
- test/globalObject/global_object_get_property.cc
- test/globalObject/global_object_has_own_property.cc
- test/globalObject/global_object_set_property.cc
- test/name.cc
- test/object/delete_property.cc
- test/object/get_property.cc
- test/object/has_own_property.cc
- test/object/has_property.cc
- test/object/object.cc
- test/object/set_property.cc
- test/object/subscript_operator.cc
- test/object_reference.cc
- test/run_script.cc
- test/type_taggable.cc
- test/typedarray.cc
Fixes: https://github.com/nodejs/node-addon-api/issues/1575
> src: enable type cast checks in tests

- napi.h
Since the first stable version of node-api, multiple environments are supported.
> doc: amend outdated doc about multiple environments

- .github/workflows/node-api-headers.yml
- napi-inl.h
- napi.h
- test/binding.gyp
Fixes: https://github.com/nodejs/node-addon-api/issues/1584
Add GitHub Actions for `node-api-headers` compatibility test, covering old Node.js versions. `node-api-headers` strips experimental apis so only test with stable NAPI_VERSION.
As there was no feature detection defs for `node_api_basic_finalize` or `node_api_basic_env`, use `NODE_API_EXPERIMENTAL_HAS_POST_FINALIZER` for feature detection since it was introduced about the time where `node_api_basic_env`/`node_api_nogc_env` was introduced.
> fix: missing node_api_nogc_env definition

- .github/workflows/release-please.yml
Generate npm provenance statement when publishing `node-addon-api`.
Refs: https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions
> chore: npm publish provenance

- doc/memory_management.md
- doc/version_management.md
- napi-inl.h
- napi.h
Fixes https://github.com/nodejs/node-addon-api/issues/1594
> fix: mark external memory and version APIs as basic

- napi-inl.h
- napi.h
According to https://nodejs.org/api/n-api.html#napi_wrap, the `napi_reference` returned from `napi_wrap` should be deleted with `napi_delete_reference`. In node-addon-api, for an `ObjectWrap`, this is done with `~Reference` destructor when the `_ref` is not `nullptr`.
To prevent `~ObjectWrap` from creating a handle during finalization, add a new flag to guard on it, instead of nullify `_ref`.
Submitted https://github.com/nodejs/node/pull/55620 to allow `napi_delete_reference` been immediately invoked in an `node_api_basic_finalizer`.
Fixes https://github.com/nodejs/node-addon-api/issues/1602
> fix: missing napi_delete_reference on ObjectWrap ref

- doc/cmake-js.md
- doc/error_handling.md
- doc/setup.md
- napi-inl.h
- napi.h
- node_addon_api.gyp
- noexcept.gypi
- test/binding.gyp
- test/except_all.cc
- test/except_all.js
Add new compile-time define (`NODE_ADDON_API_CPP_EXCEPTIONS_ALL`)  to enable catching all exceptions. This must be used _in conjunction with_ `NODE_ADDON_API_CPP_EXCEPTIONS`.
Rename the `NAPI_` prefixed exception preprocessor definitions (`NAPI_CPP_EXCEPTIONS` and `NAPI_DISABLE_CPP_EXCEPTIONS`) to be prefixed with our standard `NODE_ADDON_API_` prefix in a backwards-compatible way.
Fixes: #1555
> feat: allow catching all exceptions

- test/except_all.cc
‘std::runtime_error’ is defined in header ‘\<stdexcept\>’.
---
See failing CI builds on `fedora-last-latest` (Fedora 40) and `fedora-latest` (Fedora 41):
e.g.  https://ci.nodejs.org/job/node-test-node-addon-api-new/nodes=fedora-latest-x64/9904/console
```console
../except_all.cc: In function ‘void ThrowStdException(const Napi::CallbackInfo&)’:
../except_all.cc:7:14: error: ‘runtime_error’ is not a member of ‘std’
7 |   throw std::runtime_error(message);
|              ^~~~~~~~~~~~~
../except_all.cc:2:1: note: ‘std::runtime_error’ is defined in header ‘<stdexcept>’; this is probably fixable by adding ‘#include <stdexcept>’
1 | #include "napi.h"
+++ |+#include <stdexcept>
2 | 
make: *** [binding_except_all.target.mk:139: Release/obj.target/binding_except_all/except_all.o] Error 1
```
> fix: add missing `stdexcept` include to test

- doc/cmake-js.md
> Fix incorrect instruction in cmake.js docs

- napi-inl.h
Fixes https://github.com/nodejs/node-addon-api/issues/1639
This does not add any new version 10 APIs in C++. This fixes a semantic experimental guard with  a version 10 guard.
Refs: https://github.com/nodejs/node/pull/55676
> fix: node-api version 10 support

- napi-inl.h
- napi.h
- test/basic_types/value.cc
- test/basic_types/value.js
> feat: add sugar method for PropertyLValue (#1651)
