napi-inl.h
napi.h

I had not built this code on a Mac or with gcc for a while. GCC there is a little more pedantic, and in one case caught a bug.

Fix build errors on macOS

---

napi-inl.h
napi.h

- Rename napi_get_type_of_value to napi_typeof
- Rename napi_create_boolean to napi_get_boolean
- Add optional parameter to napi_get_value_string and napi_create_buffer_copy
- Pass size_t length when creating string values
- Rename AddRef/Release to Ref/Unref

Updates for N-API changes

---

napi-inl.h

Ref: https://github.com/nodejs/abi-stable-node/issues/227#issuecomment-294025785

Default `this` to `undefined` for function calls

---

napi-inl.h
napi.h
test/binding.cc
test/binding.gyp
test/index.js
test/name.cc
test/name.js

- Add abstract `Name` class that is the base for `String` and `Symbol` classes
- Add `Symbol` class
- Add unit tests for both `String` and `Symbol` classes

Add Symbol class

---

src/node_api.cc
src/node_api.h

Pick up changes as of nodejs/node@98609fc1c4635f02f8f6ef9dd079207a1204b9a1.

Update to current sources

---

README.md

These are the results of the recent membership review. Closes #375.

Membership review update

---

CONTRIBUTING.md
README.md

Fixes: https://github.com/nodejs/abi-stable-node/issues/363

doc: Add contribution philosophy doc

---

README.md

Re: https://github.com/nodejs/node-addon-api/pull/494#issuecomment-511996320

doc: add ThreadSafeFunction to main README

---

README.md

Kevin has been active in helping answer questions, submitting
PRs and helping to move n-api and node-addon-api forward. Believe
it's time to add him formally to the team here as well.

doc: add Kevin to the list of collaborators

---

README.md

Based on activity believe it might be time to move
to Emeritus.
@aruneshchandra @boingoing Thinking it might be time to move you two to emeritus based on you being pulled on other priorities.  
Let me know if that makes sense or not.  I've left @digitalinfinity as the MS rep whoes continuing to work on N-API/node-addon-api.

doc: move Arunesh and Taylor to Emeritus

---

test/index.js

This should fix recent CI failure on most PRs and the master branch.

test: do not run TSFN tests on NAPI_VERSION < 4

---

doc/async_worker.md

Improve AsyncWorker docs according to @gabrielschulhof's [comments](https://github.com/nodejs/node-addon-api/pull/529#pullrequestreview-300823703).

doc: improve AsyncWorker docs

---

doc/async_operations.md

Refs: https://github.com/nodejs/node/pull/23967

doc: change node.js to Node.js per guideline

---

README.md

Reference the documentation for `Napi::AsyncProgressWorker` int the `README`

doc: Added AsyncProgressWorker to readme

---

README.md

😋 Just noticed the list so I'd like to propose adding myself to it.

doc: add @legendecas to active member list

---

tools/README.md

The address-of operator is required for all class members.

Remove misleading sentence

---

.travis.yml

Refs: https://github.com/nodejs/node-addon-api/issues/469

test: remove sudo from travis

---

.github/workflows/stale.yml

action: add stale action

---

README.md

docs: add NAN to N-API resource link

---

doc/async_worker_variants.md

doc: fix typo in code example

---

doc/async_worker_variants.md
doc/error_handling.md
doc/escapable_handle_scope.md
doc/object.md
doc/object_wrap.md
doc/type_error.md
doc/typed_threadsafe_function.md

Caught and fixed some typos :)

docs: fix typos

---

doc/typed_threadsafe_function.md

doc: fix typo in TypedThreadSafeFunction example

---

doc/hierarchy.md
package.json

doc: fix broken `Napi::ThreadSafeFunction` link

---

test/promise.cc
test/promise.js

This PR closes out https://github.com/nodejs/node-addon-api/issues/1053

test: Add promise unit test

---

doc/async_operations.md

doc: fix typo in async_operations.md

---

doc/async_worker.md

doc: complete code curly braces  in async_worker.md

---

doc/value.md

doc: add missing Value::IsBigInt

---

CHANGELOG.md
README.md
package.json

Update package and documentation for release v7.0.0 according to [Creating a Release](https://github.com/nodejs/node-addon-api/blob/de5c899400fffbc2265d66c687f4f7ce585925cd/doc/creating_a_release.md)

release: v7.0.0

---

doc/value.md

I found that IsBigInt didn't have a title, so I added it.

doc: add missing title IsBigInt

---

LICENSE.md

Reformat to be similar to other licence files that GitHub does recognize. 
Formatting change only, no material change.

Update LICENSE.md so GitHub recognizes it

---

test/bigint.cc

test: remove experimental flag from bigint

---

.github/workflows/ci-win.yml
.github/workflows/ci.yml

Refs: https://github.com/nodejs/node-addon-api/pull/1401#issuecomment-1792396300
Refs: https://github.com/nodejs/node-gyp/issues/2869
Refs: https://github.com/nodejs/node-addon-api/actions/runs/6765126277

chore: lock python version in actions

---

CHANGELOG.md
README.md
package.json

CI:
| Version | Job | Status |
|---:|---|:---:|
| v22.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/8349/ | ✅ |
| v21.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/8350/ | ✅ |
| v20.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/8351/ | ✅ |
| v18.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/8356/ | ✅ |
| v16.x | https://ci.nodejs.org/job/node-test-node-addon-api-new/8357/ | ✅ |
Refs: https://github.com/nodejs/node-addon-api/issues/1381

Release v7.1.0

---

test/common/index.js

Examine `process.env.npm_config_debug` to determine whether it's a Debug or a Release build.

test: heed npm_config_debug

---

CHANGELOG.md
README.md
package.json

Closes https://github.com/nodejs/node-addon-api/issues/1381

v8.0.0 Release Proposal

---

README.md

This PR adds the codecov badge to the readme.

doc: add codecov badge to readme

---

.github/workflows/release-please.yml

Refs: https://github.com/nodejs/node-addon-api/issues/1521

chore: add release automation

---

.github/workflows/release-please.yml

Refs: https://github.com/nodejs/node-addon-api/pull/1514#issuecomment-2327322653

chore: explicitly define release please permissions

---

.github/workflows/release-please.yml

Refs: https://github.com/nodejs/admin/issues/998

chore: enable OIDC npm publishing
